---
- name: Set  systemd boot target
  hosts: all
  gather_facts: no
  become: true
  vars:
  - target: multi-user.target
  tasks:
  - command: "systemctl get-default"
    register: out
    changed_when: false
  - block: 
    - file:
        state: absent
        path: /etc/systemd/system/default.target
    - file:
        state: link
        src: "/usr/lib/systemd/system/{{target}}"
        dest: /etc/systemd/system/default.target
    when: target not in out.stdout_lines
  - command: " systemctl get-default"
    register: out
  - debug:
      var: out.stdout_lines
