---
- name: install and configure web server
  hosts: localhost
  vars:
  - http_port: 80
  - http_folder: /webfiles
  - httpd_conf: /etc/httpd/conf/httpd.conf
  - https_port: 443
  - httpd_conf_dir: /etc/httpd/conf.d/
  - https_conf: "{{ httpd_conf_dir }}/ssl.conf"
  force_handlers: true
  tasks:
  - name: install httpd
    yum:
     name: 
     - httpd
     - mod_ssl
     state: latest
  - name: Intall Selinux in Amazon
    yum:
      name: policycoreutils-python
      state: latest
    when: ansible_distribution == "Amazon"
    
  - name: enable and start http
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items: 
    - httpd

  - name: config http
    block:
    - lineinfile:
        path: "{{ httpd_conf }}"
        regexp: "^Listen"
        line: "Listen {{ http_port }}"
      notify: restart_httpd
    - name: config https
      lineinfile:
        path: "{{ https_conf }}"
        regexp: "^Listen"
        line: "Listen {{ https_port }}"
      notify: restart_httpd
    - name: Apache  VirtualHosts
      template:
        src: "{{ item }}"
        dest: "{{ httpd_conf_dir }}/{{item}}.vhost.conf"
        owner: root
        mode: '0644'
      with_items:
      - http_template.j2
      - https_template.j2
      notify: restart_httpd
 
  - name: prepare http files
    block:
    - file:
        state: directory
        path: "{{ http_folder }}/{{ ansible_facts['hostname'] }}"
    - name: Prepare index.html
      template:
        src: http_index.j2
        dest: "{{ http_folder }}/{{ ansible_facts['hostname'] }}/index.html"
    - name: Allow apache to modify files in  "{{ http_folder }}"
      sefcontext:
        target: '{{ http_folder }}(/.*)?'
        setype: httpd_sys_content_t
        state: present
      
    - name: Apply new SELinux file context to filesystem
      command: restorecon -irv  "{{ http_folder }}"
      
    - name: create symlink to share
      file:
          src: "{{ http_folder }}"
          dest: "/var/www/html/{{ http_folder }}"
          state: link
    - name: Allow Apache to listen on tcp port "{{ http_port }}"
      seport:
          ports: "{{ item }}"
          proto: tcp
          setype: http_port_t
          state: present
      with_items:
      - "{{ http_port }}"
      - "{{ https_port }}"
      notify: restart_httpd
  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restarted
...

