---
- name: collect facts
  hosts: all
  gather_facts:  yes
  tasks:
  - debug:
      msg: "Cololecting facts"
      
- name: Generate /etc/hosts 
  hosts: clients
  gather_facts: no
  tasks:
#  - debug:
#      msg: "{{ hostvars['rhce-client1'].ansible_facts }}"
  - template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      setype: net_conf_t
      mode: '0644'
  -  command: "cat /etc/hosts"
     register: stout
  - debug:
      msg: "{{ stout.stdout_lines }}"
